apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{cookiecutter.__app_name}}-prod

resources:
  - ../../base

patches:
  - target:
      kind: Certificate
      name: {{cookiecutter.__app_name}}-cert
    patch: |
      - op: replace
        path: /spec/secretName
        value: {{cookiecutter.__app_name}}-tls
      
      - op: replace
        path: /spec/commonName
        value: {{cookiecutter.__app_name}}.{{cookiecutter.external_domain}}

      - op: replace
        path: /spec/dnsNames
        value:
          - {{cookiecutter.__app_name}}.{{cookiecutter.internal_domain}}
          - {{cookiecutter.__app_name}}.${cluster_site}.{{cookiecutter.internal_domain}}
          - {{cookiecutter.__app_name}}.${cluster_instance}.${cluster_site}.{{cookiecutter.internal_domain}}
          
  - target:
      kind: Gateway
      name: {{cookiecutter.__app_name}}-ingress
    patch: |
      - op: replace
        path: /spec/servers/0/hosts
        value:
          - {{cookiecutter.__app_name}}.{{cookiecutter.external_domain}}
          - {{cookiecutter.__app_name}}.{{cookiecutter.internal_domain}}
          - {{cookiecutter.__app_name}}.${cluster_site}.{{cookiecutter.internal_domain}}
          - {{cookiecutter.__app_name}}.${cluster_instance}.${cluster_site}.{{cookiecutter.internal_domain}}
      
      - op: replace
        path: /spec/servers/0/tls/credentialName
        value: {{cookiecutter.__app_name}}-tls

  - target:
      kind: VirtualService
      name: {{cookiecutter.__app_name}}-vs
    patch: |
      - op: replace
        path: /spec/http/0/route/0/destination/host
        value: {{cookiecutter.__app_name}}-service.{{cookiecutter.__app_name}}-prod.svc.cluster.local