apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{cookiecutter.__app_name}}

resources:
  - certificate.yaml
  - deployment.yaml
  - hpa.yaml
  - ingress-gateway.yaml
  - service.yaml
  - virtual-service.yaml